"""Add log_pulls table

Revision ID: 6693db3f1d68
Revises: fec829d9ec83
Create Date: 2026-10-01 23:25:37.805989

Hand-written rather than autogenerated. `wsgi.py` calls `db.create_all()` at
import, so by the time `flask db migrate` compared metadata the table already
existed and autogenerate emitted nothing for it — while sweeping in unrelated
pre-existing drift on `template_applications` and `waas_accounts`. That drift
is not this change's business and has been removed; only log_pulls is here.

`create_all` means the table may already exist on a running instance, so the
upgrade is written to be a no-op in that case.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6693db3f1d68'
down_revision = 'fec829d9ec83'
branch_labels = None
depends_on = None

TABLE = 'log_pulls'


def _exists(name):
    bind = op.get_bind()
    return sa.inspect(bind).has_table(name)


def upgrade():
    if _exists(TABLE):
        return

    op.create_table(
        TABLE,
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('app_id', sa.String(length=255), nullable=False),
        sa.Column('app_name', sa.String(length=255), nullable=False),

        # plan
        sa.Column('mode', sa.String(length=10), nullable=False),
        sa.Column('window_days', sa.Integer(), nullable=False),
        sa.Column('range_start', sa.Integer(), nullable=False),
        sa.Column('range_end', sa.Integer(), nullable=False),
        sa.Column('sample_window_seconds', sa.Integer(), nullable=False),
        sa.Column('sample_slot_seconds', sa.Integer(), nullable=False),

        # lifecycle
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('session_id', sa.String(length=36), nullable=False),
        sa.Column('cancel_requested', sa.Boolean(), nullable=False,
                  server_default=sa.false()),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),

        # durable progress
        sa.Column('phase', sa.String(length=20), nullable=False),
        sa.Column('rows_expected', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('rows_fetched', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('pages_fetched', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('days_total', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('days_done', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('bytes_on_disk', sa.BigInteger(), nullable=False, server_default='0'),
        sa.Column('current_window_start', sa.Integer(), nullable=True),
        sa.Column('eta_seconds', sa.Integer(), nullable=True),
        sa.Column('truncated_windows', sa.Integer(), nullable=False, server_default='0'),

        # retention
        sa.Column('raw_expires_at', sa.DateTime(), nullable=True),
        sa.Column('raw_deleted', sa.Boolean(), nullable=False, server_default=sa.false()),

        # results
        sa.Column('result_data', sa.Text(), nullable=True),
        sa.Column('report_data', sa.Text(), nullable=True),

        sa.ForeignKeyConstraint(['account_id'], ['waas_accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table(TABLE, schema=None) as batch_op:
        batch_op.create_index(op.f('ix_log_pulls_account_id'), ['account_id'], unique=False)
        batch_op.create_index(op.f('ix_log_pulls_app_id'), ['app_id'], unique=False)
        batch_op.create_index(op.f('ix_log_pulls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(op.f('ix_log_pulls_raw_expires_at'), ['raw_expires_at'], unique=False)
        batch_op.create_index(op.f('ix_log_pulls_session_id'), ['session_id'], unique=True)
        batch_op.create_index(op.f('ix_log_pulls_status'), ['status'], unique=False)
        batch_op.create_index(op.f('ix_log_pulls_user_id'), ['user_id'], unique=False)


def downgrade():
    if not _exists(TABLE):
        return
    with op.batch_alter_table(TABLE, schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_log_pulls_user_id'))
        batch_op.drop_index(op.f('ix_log_pulls_status'))
        batch_op.drop_index(op.f('ix_log_pulls_session_id'))
        batch_op.drop_index(op.f('ix_log_pulls_raw_expires_at'))
        batch_op.drop_index(op.f('ix_log_pulls_created_at'))
        batch_op.drop_index(op.f('ix_log_pulls_app_id'))
        batch_op.drop_index(op.f('ix_log_pulls_account_id'))
    op.drop_table(TABLE)
