"""baseline from v1 seed

Revision ID: 8f4d20c89301
Revises: 
Create Date: 2026-08-12 15:32:45.591280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4d20c89301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_failed_login', sa.DateTime(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('show_technical', sa.Boolean(), nullable=True),
    sa.Column('notify_report_email', sa.Boolean(), nullable=True),
    sa.Column('notify_report_inapp', sa.Boolean(), nullable=True),
    sa.Column('notify_cert_expiry_email', sa.Boolean(), nullable=True),
    sa.Column('notify_cert_expiry_inapp', sa.Boolean(), nullable=True),
    sa.Column('notify_apikey_expiry_email', sa.Boolean(), nullable=True),
    sa.Column('notify_apikey_expiry_inapp', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('config_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_data', sa.Text(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_templates_is_global'), ['is_global'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_templates_user_id'), ['user_id'], unique=False)

    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('config_data', sa.Text(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('is_predefined', sa.Boolean(), nullable=True),
    sa.Column('api_endpoint', sa.String(length=255), server_default='/applications/{app_id}/import/', nullable=False),
    sa.Column('api_method', sa.String(length=10), server_default='PATCH', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_is_global'), ['is_global'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_is_predefined'), ['is_predefined'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('waas_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('waas_account_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('api_key_expiry', sa.Date(), nullable=True),
    sa.Column('waas_email_encrypted', sa.Text(), nullable=True),
    sa.Column('waas_password_encrypted', sa.Text(), nullable=True),
    sa.Column('v2_auth_token_encrypted', sa.Text(), nullable=True),
    sa.Column('v2_token_expiry', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waas_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waas_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('account_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['waas_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'user_id', name='uq_account_share')
    )
    with op.batch_alter_table('account_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_shares_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_shares_user_id'), ['user_id'], unique=False)

    op.create_table('feature_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['waas_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id', 'account_id', 'app_name', name='uq_feature_app')
    )
    with op.batch_alter_table('feature_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_applications_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_applications_feature_id'), ['feature_id'], unique=False)

    op.create_table('proxy_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('cname', sa.String(length=255), nullable=True),
    sa.Column('cname_ip', sa.String(length=45), nullable=True),
    sa.Column('display_number', sa.Integer(), nullable=True),
    sa.Column('vnc_port', sa.Integer(), nullable=True),
    sa.Column('websocket_port', sa.Integer(), nullable=True),
    sa.Column('xvfb_pid', sa.Integer(), nullable=True),
    sa.Column('chromium_pid', sa.Integer(), nullable=True),
    sa.Column('vnc_pid', sa.Integer(), nullable=True),
    sa.Column('websockify_pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['waas_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proxy_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proxy_sessions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('scheduled_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['waas_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_reports_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_reports_user_id'), ['user_id'], unique=False)

    op.create_table('template_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['waas_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['config_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'account_id', 'app_name', name='uq_template_app')
    )
    with op.batch_alter_table('template_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_applications_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_applications_template_id'), ['template_id'], unique=False)

    op.create_table('report_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['scheduled_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_runs_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_runs_report_id'))

    op.drop_table('report_runs')
    with op.batch_alter_table('template_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_applications_template_id'))
        batch_op.drop_index(batch_op.f('ix_template_applications_account_id'))

    op.drop_table('template_applications')
    with op.batch_alter_table('scheduled_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_reports_account_id'))

    op.drop_table('scheduled_reports')
    with op.batch_alter_table('proxy_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proxy_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_proxy_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_proxy_sessions_account_id'))

    op.drop_table('proxy_sessions')
    with op.batch_alter_table('feature_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_applications_feature_id'))
        batch_op.drop_index(batch_op.f('ix_feature_applications_account_id'))

    op.drop_table('feature_applications')
    with op.batch_alter_table('account_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_shares_user_id'))
        batch_op.drop_index(batch_op.f('ix_account_shares_account_id'))

    op.drop_table('account_shares')
    with op.batch_alter_table('waas_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waas_accounts_user_id'))

    op.drop_table('waas_accounts')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_user_id'))
        batch_op.drop_index(batch_op.f('ix_features_is_predefined'))
        batch_op.drop_index(batch_op.f('ix_features_is_global'))
        batch_op.drop_index(batch_op.f('ix_features_category'))

    op.drop_table('features')
    with op.batch_alter_table('config_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_config_templates_is_global'))

    op.drop_table('config_templates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
