"""add site_profiles table

Revision ID: b62bc65e5f2c
Revises: 8f4d20c89301
Create Date: 2026-08-12 17:50:35.845380

Autogenerate also picked up drift on template_applications / waas_accounts
between the baseline (autogenerated from models) and the live v1-seeded DB.
Those unrelated diffs have been stripped from this migration — they belong
in a dedicated "reconcile v1 seed drift" migration if/when we decide to
apply them.

"""
from alembic import op
import sqlalchemy as sa


revision = 'b62bc65e5f2c'
down_revision = '8f4d20c89301'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'site_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('target_url', sa.String(length=2048), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('session_id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('profile_data', sa.Text(), nullable=True),
        sa.Column('recommendation_data', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['waas_accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('site_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_site_profiles_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_site_profiles_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_site_profiles_status', ['status'], unique=False)
        batch_op.create_index('ix_site_profiles_session_id', ['session_id'], unique=True)
        batch_op.create_index('ix_site_profiles_created_at', ['created_at'], unique=False)


def downgrade():
    with op.batch_alter_table('site_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_site_profiles_created_at')
        batch_op.drop_index('ix_site_profiles_session_id')
        batch_op.drop_index('ix_site_profiles_status')
        batch_op.drop_index('ix_site_profiles_account_id')
        batch_op.drop_index('ix_site_profiles_user_id')
    op.drop_table('site_profiles')
